const ConditionsofUse = () => {
    return(
    <div className="container terms">
        <h1>condition of use.</h1>
        <p>
            <strong>Welcome to KFMCart.com</strong>. KFM Enterprises Private Limited and its affiliates provide access to the KFMCart.com
            website (the "website") to you subject to the conditions set out on this page.
        </p>
        <p>
             Please read these conditions carefully before using the KFMCart.com website. By using the KFMCart.com website, you signify your agreement to be bound by these conditions.
        </p>
        <p>
            In addition, when you use any current or future KFMCart.com service ("KFMCart Service"), you will also be subject to the terms, guidelines and conditions applicable to that KFMCart Service. ("Terms"). If these Conditions of Use are inconsistent with such Terms, the Terms will control.
        </p>
        <p>
            These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>
        <ul>
            <li>Conditions Relating to Your Use of KFMCart.com</li>
            <li>Notice and Procedure for Making Claims of Infringement</li>
            <li>Notice and Procedure for Notifying Amazon.in of Objectionable Content</li>
        </ul>
        
    </div>)
}
  
export default ConditionsofUse